name: Deploy Test

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Deploy to test environment
      run: |
        # Add your deployment steps here for the test environment
        # This might be similar to the production deployment,
        # but targeting a different server or environment